name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: command testing action
      uses: MeilCli/test-command-action@v1
      with:  
        command: 
          mvn clean test
    - name: xUnit Slack Reporter
      uses: ivanklee86/xunit-slack-reporter@v1.0.1
